#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep wifi | awk '{print ($1)}')
external_ip=$(curl -s https://ipinfo.io/ip)

if [ $status ] ; then
    icon="睊"
    text=""
    col="#575268"

else
    icon="直"
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
elif [[ "$1" == "--EXIP" ]]; then
	echo $external_ip
fi

